import Anthropic from "@anthropic-ai/sdk";
import { NextResponse } from "next/server";

import {
  FILL_TOOL_NAME,
  KEEP_OUT_NOTE,
  LIMITS,
  checkMessages,
  confirmation,
  createLimiter,
  fillTool,
  mentionsEmail,
  systemPrompt,
  tidyReply,
  todayInGalveston,
  todayLine,
  validateFill,
  type Room,
} from "@/lib/meraki-inn-chat";
import inn from "@/lib/meraki-inn-knowledge.json";

/**
 * The assistant on The Meraki Inn demo (/demos/meraki-inn). It answers
 * questions from the demo's own pages and can fill in three fields of the
 * date request form: arrival date, nights and room.
 *
 * Like the restaurant demo's route, this is a public, unauthenticated page
 * that spends money, so the order below is cheapest check first: rate limit,
 * body size, shape of the conversation, card numbers. Only a request that
 * passes all of them reaches the provider.
 *
 * What the model can and cannot do is in lib/meraki-inn-chat.ts, with tests
 * in scripts/tests. The short version:
 *  - It has no data store, no network and no code execution. Its knowledge is
 *    the text of the demo's pages, generated by scripts/demos/meraki-inn/build.py
 *    into lib/meraki-inn-knowledge.json, so the site and the assistant cannot
 *    drift apart.
 *  - It has one tool. The tool's input is treated as a form post from a
 *    stranger and validated here before the browser ever sees it.
 *  - The dollar figures in a confirmation are computed here, not by the model.
 *  - Today's date comes from this server, never from the browser.
 *
 * Nothing is persisted. The conversation lives in the visitor's browser tab
 * and is replayed on each turn. The log line records token counts, never text.
 */

/** Same model as the restaurant demo's assistant, which is in production on this key. */
const MODEL = "claude-sonnet-4-6";

/** Replies are a few sentences. The tool call is three short fields. */
const MAX_TOKENS = 500;

const limited = createLimiter(15, 60 * 1000); // 15 requests a minute, per address

const ROOMS: readonly Room[] = inn.rooms;
const PHONE: string = inn.phone;

// Built once per server instance. This block is identical on every request,
// which is what lets the provider cache it.
const SYSTEM = systemPrompt(inn.knowledge, ROOMS, PHONE);
const TOOL = fillTool(ROOMS);

const client = new Anthropic();

function clientIp(req: Request): string {
  const forwarded = req.headers.get("x-forwarded-for");
  if (forwarded) return forwarded.split(",")[0]?.trim() || "unknown";
  return req.headers.get("x-real-ip")?.trim() || "unknown";
}

function fail(error: string, status: number, extra: Record<string, unknown> = {}) {
  return NextResponse.json({ error, ...extra }, { status });
}

export async function POST(req: Request) {
  if (limited(clientIp(req))) {
    return fail("That is a lot of questions at once. Give it a minute and try again.", 429);
  }

  // Read as text first so an oversized body is refused before it is parsed.
  const text = await req.text().catch(() => "");
  if (text.length > LIMITS.bodyChars) {
    return fail("That message is too long. Start over to keep going.", 413);
  }
  let body: unknown = null;
  try {
    body = JSON.parse(text);
  } catch {
    body = null;
  }

  const checked = checkMessages((body as { messages?: unknown } | null)?.messages, PHONE);
  if (!checked.ok) {
    return fail(checked.error, checked.status, checked.card ? { card: true } : {});
  }

  // A key that is present but empty is the same as no key at all, and it is
  // the more likely failure: Vercel's sensitive variables pull down blank.
  if (!process.env.ANTHROPIC_API_KEY?.trim()) {
    return fail("The inn's assistant is not switched on right now. Please call the inn instead.", 503);
  }

  const today = todayInGalveston();

  try {
    // `thinking` is deliberately omitted: on Sonnet 4.6 that means no
    // reasoning pass, so the whole budget goes to the visible reply.
    const response = await client.messages.create({
      model: MODEL,
      max_tokens: MAX_TOKENS,
      system: [
        { type: "text", text: SYSTEM, cache_control: { type: "ephemeral" } },
        { type: "text", text: todayLine(today) },
      ],
      tools: [TOOL],
      output_config: { effort: "low" },
      messages: checked.messages,
    });

    const call = response.content.find(
      (block): block is Anthropic.ToolUseBlock =>
        block.type === "tool_use" && block.name === FILL_TOOL_NAME,
    );

    console.log(
      `[meraki-inn-chat] in=${response.usage.input_tokens} cached=${response.usage.cache_read_input_tokens ?? 0} wrote=${response.usage.cache_creation_input_tokens ?? 0} out=${response.usage.output_tokens}/${MAX_TOKENS} stop=${response.stop_reason} fill=${call ? "yes" : "no"} model=${response.model}`,
    );

    if (response.stop_reason === "refusal") {
      return NextResponse.json({
        error: "I can't help with that one. Ask me about the inn or your dates instead.",
      });
    }

    if (call) {
      const result = validateFill(call.input, ROOMS, today);
      if (!result.ok) {
        return NextResponse.json({
          reply: `${result.reason} Tell me the arrival date, the number of nights and the room, and I will try again.`,
        });
      }
      // The confirmation is ours, so the model's own reminder is lost with its
      // text. If the visitor just typed an email address, say it here instead.
      const latest = checked.messages[checked.messages.length - 1].content;
      const note = mentionsEmail(latest) ? `\n\n${KEEP_OUT_NOTE}` : "";
      return NextResponse.json({
        reply: confirmation(result.fill, ROOMS, today) + note,
        fill: result.fill,
      });
    }

    const reply = tidyReply(
      response.content
        .filter((block): block is Anthropic.TextBlock => block.type === "text")
        .map((block) => block.text)
        .join(""),
    );

    if (!reply) {
      return fail("Sorry, I lost my place there. Try that again?", 502);
    }

    return NextResponse.json({ reply });
  } catch (error) {
    // Most specific first. The visitor never sees provider detail; the server
    // log gets the message only, never the error object, because a thrown
    // client error can carry request context.
    if (error instanceof Anthropic.AuthenticationError) {
      console.error("[meraki-inn-chat] auth rejected by Anthropic");
      return fail("The inn's assistant is not switched on right now. Please call the inn instead.", 503);
    }
    if (error instanceof Anthropic.RateLimitError) {
      return fail("The front desk is busy. Try again in a moment.", 429);
    }
    if (error instanceof Anthropic.APIError) {
      console.error(`[meraki-inn-chat] API error ${error.status}`);
      return fail("Something went wrong on our end. Try again in a moment.", 502);
    }
    console.error(
      "[meraki-inn-chat] unexpected:",
      error instanceof Error ? error.message : "unknown",
    );
    return fail("Something went wrong on our end. Try again in a moment.", 500);
  }
}
