"""Page content for The Meraki Inn demo. See mi.py for what is real and what is a sample.

Each inner page is a dict: the hour it opens on, its headline, and a list of
sections that build.py knows how to draw. Facts were checked on October 2, 2026:
Port of Galveston (terminals), Galveston Historical Foundation (Dickens on The
Strand), mardigrasgalveston.com (2027 dates), Texas Comptroller and City of
Galveston (hotel occupancy tax), National Hurricane Center and National Weather
Service (advisories, watch and warning), ASCE and the National Park Service
(Seawall, grade raising, East End Historic District), TxDOT (Bolivar ferry).
"""
from mi import ROOMS, PHONE

HOME_TITLE = "Boutique Inn in Galveston's East End | The Meraki Inn"
HOME_DESC = ("The Meraki Inn is a five room boutique inn in Galveston's East End Historic District, with breakfast on the gallery "
             "and a short bike ride to the beach.")

HOME_FAQ = [
    ("Where is The Meraki Inn?", "In Galveston's East End Historic District, between Broadway and Market Street. The Strand and the beach are both a short bike ride away, and we keep six bikes by the side gate."),
    ("What does meraki mean?", "It is a Greek word for doing something with soul, creativity and love, so that a piece of you ends up in the work. Each room is furnished around one craft, made by hand in Texas."),
    ("Is breakfast included?", "Yes. Coffee is out at 6:30, and breakfast is cooked to order on the gallery from 8 to 9:30."),
    ("What time is check in?", "Check in is from 3 PM to 8 PM, and check out is by 11 AM. Call if you will arrive later and we will leave the porch light on."),
    ("How many rooms does the inn have?", "Five. Four are in the 1894 house and one is a suite in the carriage house. Sample rates run from $189 to $289 a night with breakfast."),
    ("Can I park at the inn while I am on a cruise?", 'Yes. Guests who stay the night before a cruise can leave a car in our gated lot for $12 a day. That is a sample rate for this demo. See <a href="cruise-parking.html">the night before a cruise</a>.'),
    ("What happens if a hurricane is forecast?", 'Hurricane season runs from June 1 to November 30. If a hurricane warning is issued for Galveston during your dates, we refund the stay in full. See <a href="hurricane-season.html">hurricane season</a>.'),
]

# ------------------------------------------------------------------ rooms
ROOM_PAGES = {
    "the-loom": {
        "title": "The Loom, Corner King Room | The Meraki Inn",
        "desc": "The Loom is a corner king room on the second floor of The Meraki Inn in Galveston, with a bay window, a door to the gallery and linens from a Texas weaver.",
        "tone": "dawn", "when": "First light", "clock": ("live", "sunrise", "Sunrise"),
        "h1": "The Loom, the corner room that gets the sun first",
        "lede": "A king bed, a bay window on two sides and a door straight onto the upstairs gallery. $249 a night with breakfast.",
        "checks": ["King bed in a black iron frame", "Bay window on the east and south sides", "Its own door to the upstairs gallery",
                   "Walk in shower with a rain head", "Linen curtains and indigo throws, woven in Texas", "Ceiling fan, central air and fast wifi"],
        "story_title": "Why is it called The Loom?",
        "story": ["<b>Every room at the inn is furnished around one craft, and this one is weaving.</b> The curtains are plain weave linen, heavy enough to hang straight and light enough to lift when the bay window is open.",
                  "The throw at the foot of the bed is dyed with indigo, and no two of them match. We ask every maker for the same thing: something a guest will touch every day of the stay. Here that is the cloth."],
        "bath": "Walk in shower", "know": "The only room with a door straight onto the gallery",
        "faq": [("Which room gets the best morning light?", "The Loom. It sits on the southeast corner of the house, so the bay window takes the sunrise before any other room."),
                ("Can two people share The Loom?", "Yes. Every room at the inn sleeps two, and The Loom has one king bed."),
                ("Is the gallery private?", "The upstairs gallery is shared by the second floor rooms and it is where breakfast is served. The Loom is the only room with its own door onto it.")],
    },
    "the-kiln": {
        "title": "The Kiln, Queen Room with a Tub | The Meraki Inn",
        "desc": "The Kiln is a queen room on the second floor of The Meraki Inn in Galveston, with deep green walls, a clawfoot tub by the window and hand thrown pottery.",
        "tone": "morning", "when": "Before breakfast", "clock": ("fixed", "7:00", "AM"),
        "h1": "The Kiln, a green room with a tub by the window",
        "lede": "A queen bed, deep green walls and a clawfoot tub under the tall window. The quietest room in the house, $219 a night with breakfast.",
        "checks": ["Queen bed", "Clawfoot tub with brass taps and a hand shower", "Lamps, tiles and a washbasin thrown by a Galveston potter",
                   "At the back of the house, over the garden", "A wooden blind for the window by the tub", "Ceiling fan, central air and fast wifi"],
        "story_title": "Why is it called The Kiln?",
        "story": ["<b>The craft in this room is pottery.</b> The lamps on either side of the bed, the tiles behind the tub and the washbasin were all thrown and fired on the island.",
                  "The walls went green to match one glaze. It took four tries to get the paint right, and the potter still says the basin is the better color."],
        "bath": "Clawfoot tub with a hand shower", "know": "The quietest room, at the back of the house",
        "faq": [("Does The Kiln have a shower?", "The tub has a hand shower on a brass cradle. If you would rather have a walk in shower, ask for The Loom, The Bindery or The Press."),
                ("Why is The Kiln the quietest room?", "It faces the back garden, away from the street, and it shares only one wall with the stair hall."),
                ("Is the tub hard to climb into?", "The rim is about two feet high. Guests who would rather not step over it are happier in The Press, which has a shower with a low threshold and a bench.")],
        "tall": True,
    },
    "the-press": {
        "title": "The Press, Step Free Queen Room | The Meraki Inn",
        "desc": "The Press is a first floor queen room at The Meraki Inn in Galveston, reached from the side porch without a step, with a writing desk and letterpress prints.",
        "tone": "noon", "when": "The writing hour", "clock": ("fixed", "2:00", "PM"),
        "h1": "The Press, the first floor room with no steps",
        "lede": "A queen bed on the first floor, reached from the side porch without a single step. $189 a night with breakfast.",
        "checks": ["Queen bed in an oak frame", "Step free from the gated lot, by the side porch ramp", "Shower with a low threshold, a bench and a grab bar",
                   "Letterpress prints of old island charts", "A writing desk with paper, pens and a lamp", "Its own glass door to the side porch"],
        "story_title": "Why is it called The Press?",
        "story": ["<b>The prints over the bed were pulled by hand, one sheet at a time, on a press older than the house.</b> They are charts of the island and the bay, redrawn from old surveys.",
                  "The desk is there because guests kept asking for one. There is paper in the drawer and a stamp for the envelope, and the mailbox is at the front gate."],
        "bath": "Shower with a low threshold and a bench", "know": "No steps between the parking lot and the bed",
        "faq": [("Is The Press accessible?", f"It is step free from the gated lot to the bed, the door is 34 inches wide, and the shower has a low threshold, a bench and a grab bar. It is an old house and this is our most reachable room, so call {PHONE} and we will tell you exactly what is there."),
                ("Can I hear the kitchen from The Press?", "A little, from about 6 in the morning. Most guests in this room tell us it smells like breakfast before it sounds like it."),
                ("Is breakfast served on the first floor?", "Yes. We bring breakfast to the side porch outside your door, so the stairs to the gallery are never needed.")],
    },
    "the-bindery": {
        "title": "The Bindery, Queen Room with Books | The Meraki Inn",
        "desc": "The Bindery is a queen room on the second floor of The Meraki Inn in Galveston, with a wall of books, a reading chair and a hand bound guest journal.",
        "tone": "night", "when": "The reading hour", "clock": ("fixed", "10:00", "PM"),
        "h1": "The Bindery, a room lined with books",
        "lede": "A queen bed, a wall of shelves and a deep chair by the shutters. $209 a night with breakfast.",
        "checks": ["Queen bed in a carved walnut frame", "A wall of books you are welcome to read", "A hand bound journal that guests write in",
                   "A reading chair and a good lamp", "Shutters that close the room to the street", "Walk in shower, central air and fast wifi"],
        "story_title": "Why is it called The Bindery?",
        "story": ["<b>The journal on the nightstand was sewn and bound by hand, and it is the third one.</b> Guests have filled two since we opened in 2016, and both are on the shelf.",
                  "The books came with the house, from estate sales, and from guests. Take one home if you leave one behind. That is how the shelves have stayed full."],
        "bath": "Walk in shower", "know": "At the front of the house, over the entry hall",
        "faq": [("Can I take a book home?", "Take one and leave one. That is how the shelves have stayed full since 2016."),
                ("Is there a television in the room?", "No room at the inn has one. There is fast wifi in every room, and in this one there is a wall of books."),
                ("Which floor is The Bindery on?", "The second floor, at the front of the house, over the entry hall. The shutters keep the street out.")],
    },
    "the-darkroom": {
        "title": "The Darkroom, Carriage House Suite | The Meraki Inn",
        "desc": "The Darkroom is a king suite in the carriage house at The Meraki Inn in Galveston, with a vaulted ceiling, a sitting corner and the inn's only private porch.",
        "tone": "golden", "when": "Porch hour", "clock": ("live", "golden", "Golden hour"),
        "h1": "The Darkroom, a suite in the carriage house",
        "lede": "A king bed under a vaulted ceiling, a sitting corner, and the only private porch at the inn. $289 a night with breakfast.",
        "checks": ["King bed", "A sitting corner with a leather chair", "A private porch with a rocking chair",
                   "Silver prints of the Gulf, made by hand from film", "Walk in shower and a dressing room", "Children of any age are welcome here"],
        "story_title": "Why is it called The Darkroom?",
        "story": ["<b>Every photograph in the suite was printed by hand in a darkroom, from film.</b> They show the Gulf in every kind of weather, and the pier in most of them is gone now.",
                  "The carriage house once held a buggy and a hayloft. The loft floor came out to make the vaulted ceiling, and the big doors became the French doors to the porch."],
        "bath": "Walk in shower and a dressing room", "know": "The only room where children under 12 can stay",
        "faq": [("Can we bring children?", "Yes. The carriage house is the one place at the inn where children under 12 can stay. A rollaway bed is $25 a night, a sample rate for this demo."),
                ("How far is the carriage house from the main house?", "About thirty steps across the garden. Breakfast is served on the gallery of the main house, or we bring a tray to your porch."),
                ("Is the porch private?", "Yes. It faces the garden and belongs to the suite alone.")],
        "tall": True,
    },
}

ROOMS_HUB = {
    "slug": "rooms", "nav": "rooms", "crumbs": [("Home", "index.html"), ("Rooms", "")],
    "title": "Rooms at The Meraki Inn | Galveston's East End",
    "desc": "Five rooms at The Meraki Inn in Galveston: four in the 1894 house and a suite in the carriage house, each furnished around one craft. Breakfast included.",
    "tone": "night", "when": "Lamplight", "clock": ("live", "sunset", "Sunset"), "pic": "room-bindery",
    "h1": "Five rooms, each furnished around one craft",
    "lede": "Four rooms in the house and a suite in the carriage house. Every rate includes breakfast on the gallery.",
    "choose": [("For the morning light", 'The Loom, on the southeast corner. <a href="the-loom.html">See The Loom</a>.'),
               ("For a long bath", 'The Kiln, with a clawfoot tub by the window. <a href="the-kiln.html">See The Kiln</a>.'),
               ("For no stairs", 'The Press, step free from the gated lot. <a href="the-press.html">See The Press</a>.'),
               ("For a rainy day", 'The Bindery, with a wall of books. <a href="the-bindery.html">See The Bindery</a>.'),
               ("For a family, or a porch of your own", 'The Darkroom, in the carriage house. <a href="the-darkroom.html">See The Darkroom</a>.')],
    "faq": [("Does every room have a private bath?", "Yes. Four rooms have a walk in shower, and The Kiln has a clawfoot tub with a hand shower."),
            ("Is breakfast included in every rate?", "Yes. Coffee is out at 6:30 and breakfast is cooked to order from 8 to 9:30, for every guest."),
            ("Which room has no stairs?", "The Press. It is on the first floor and is step free from the gated lot, by the side porch ramp."),
            ("Do you have a room for three?", "The Darkroom. It is a suite in the carriage house, and a rollaway bed is $25 a night, a sample rate for this demo.")],
}

# ------------------------------------------------------------------ other pages
TERMINALS = [
    ("Terminal 10", "1402 Harborside Drive", "Royal Caribbean"),
    ("Terminal 16", "Pier 16, Harborside Drive", "MSC and Norwegian. Opened in November 2025, with the port's first parking garage on site."),
    ("Terminal 25", "2502 Harborside Drive", "Carnival"),
    ("Terminal 28", "2702 Harborside Drive", "Disney, Princess and Carnival"),
]

PAGES = [
    {
        "slug": "breakfast", "nav": "breakfast", "crumbs": [("Home", "index.html"), ("Breakfast", "")],
        "title": "Breakfast on the Gallery | The Meraki Inn",
        "desc": "Breakfast at The Meraki Inn is cooked to order from 8 to 9:30 and served on the upstairs gallery. Coffee is out at 6:30, and it is included in every rate.",
        "tone": "morning", "when": "Breakfast", "clock": ("fixed", "8:00", "AM"), "pic": "breakfast",
        "h1": "Breakfast is cooked to order and eaten on the gallery",
        "lede": "Coffee is out in the hall at 6:30. Isadora cooks from 8 to 9:30, and every rate includes it.",
        "sections": [
            ("lead", {"label": "The cook", "title": "Who cooks breakfast?", "paras": [
                "<b>Isadora Fontenot has cooked every breakfast at the inn since it opened in 2016.</b> She bakes before sunrise, so there is something warm on the hall table with the coffee, and she cooks the rest to order once you sit down.",
                "Breakfast is served upstairs on the gallery, where the palms are at eye level. On a cold or wet morning it moves to the dining room, by the fire.",
                "The fig preserves are hers, from the tree by the carriage house. Guests ask for a jar often enough that we keep a few by the front door."]}),
            ("table", {"bg": "mist", "title": "What is for breakfast this week?", "head": ["Day", "From the oven", "From the stove"],
                       "rows": [("Monday", "Fig and pecan scones", "Soft scrambled eggs with Gulf shrimp and chives"),
                                ("Tuesday", "Buttermilk biscuits", "Migas with salsa verde"),
                                ("Wednesday", "Apricot kolaches", "Baked eggs with tomato and basil"),
                                ("Thursday", "Banana bread", "Grits with roasted poblano and cheddar"),
                                ("Friday", "Orange rolls", "An omelet, made the way you ask"),
                                ("Saturday", "Pecan sticky buns", "Pain perdu with Texas peaches"),
                                ("Sunday", "Buttermilk biscuits", "Shrimp and grits")],
                       "caption": "A sample week for this demo. The menu follows the market, and fruit, yogurt and granola are out every day."}),
            ("rows", {"label": "Your morning", "title": "What if my morning is different?", "intro": "Tell us when you book, or the night before. Isadora cooks to order, so most things are easy.",
                      "items": [("I am leaving early for a cruise or a flight", "Tell us the night before and a breakfast bag is on the hall table from 6:30."),
                                ("I do not eat meat, gluten or dairy", "Tell us when you book and breakfast is planned around you."),
                                ("I would like breakfast on my own porch", "Guests in The Press and The Darkroom can have a tray on their porch."),
                                ("I only want coffee", "It is out at 6:30 with the morning's baking, and there is tea beside it.")]}),
        ],
        "faq_title": "Breakfast, answered",
        "faq": [("Is breakfast included in the rate?", "Yes, for every guest in every room."),
                ("What time is breakfast at the inn?", "Coffee and the morning's baking are out at 6:30. Breakfast is cooked to order from 8 to 9:30."),
                ("Can you cook for food allergies?", f"For most, yes. Our kitchen is small and handles wheat, nuts, shellfish and dairy every day, so we cannot promise that a dish is free of traces. Call {PHONE} and we will be straight with you about what we can do."),
                ("Can people who are not staying come to breakfast?", "No. Breakfast is for guests of the inn.")],
        "more": [("rooms.html", "See the rooms"), ("about.html", "Who keeps the inn")],
    },
    {
        "slug": "the-island", "nav": "island", "crumbs": [("Home", "index.html"), ("The island", "")],
        "title": "What Is Near the Inn | The Meraki Inn, Galveston",
        "desc": "What is near The Meraki Inn in Galveston: the East End Historic District, The Strand, the Seawall and beach, the free Bolivar ferry and the year's festivals.",
        "tone": "noon", "when": "The island", "clock": ("fixed", "11:00", "AM"), "pic": "bikes",
        "h1": "Everything on this end of the island is a bike ride from the porch",
        "lede": "The inn sits in the East End, between the old harbor streets and the Gulf. Six bikes wait by the side gate, free for guests.",
        "sections": [
            ("rows", {"label": "Close by", "title": "What is near the inn?", "intro": "Four places guests ask about before anything else, and one street they find on their own.", "island": True,
                      "extra": [("The Strand", "The old commercial street by the harbor, about half a mile from the inn. Its Victorian buildings hold shops, galleries and restaurants now.")]}),
            ("table", {"bg": "mist", "title": "What is on the island's calendar?", "head": ["When", "What", "Good to know"],
                       "rows": [("December 4 to 6, 2026", '<a href="dickens-on-the-strand.html">Dickens on The Strand</a>', "The 53rd year. Friday evening is free, and Saturday and Sunday are ticketed."),
                                ("January 29 to 31, 2027", "Mardi Gras! Galveston, first weekend", "Parades downtown and along the Seawall."),
                                ("February 5 to 7, 2027", "Mardi Gras! Galveston, second weekend", "Fat Tuesday follows on February 9, 2027."),
                                ("June 1 to November 30", '<a href="hurricane-season.html">Hurricane season</a>', "A hurricane warning for the island during your dates means a full refund."),
                                ("Every day", "The Bolivar ferry", "Free, and it runs 24 hours a day.")],
                       "caption": "Dates from the Galveston Historical Foundation, Mardi Gras! Galveston and the Texas Department of Transportation, checked October 2, 2026."}),
            ("lead", {"bg": "dark", "label": "The name", "title": "Why is Galveston called the Oleander City?", "paras": [
                "<b>The name has been in print since at least 1874.</b> That January the Galveston Daily News suggested that Oleander City suited the town better than Island City.",
                "The streets were lined with oleanders then, and many still are. Ours bloom pink along the front fence from spring into fall."]}),
            ("rows", {"label": "Getting around", "title": "How do guests get around?", "intro": "Most guests park once and leave the car until they go home.",
                      "items": [("By bicycle", "Six cruisers with baskets and locks wait by the side gate. They are free for guests, first come."),
                                ("On foot", "The East End is flat and shaded, and the porches are worth the walk on their own."),
                                ("By car", "Leave it in the gated lot behind the house. You will want it for the west end of the island."),
                                ("By ferry", "Walk on or drive on at the east end of the island. The crossing to the Bolivar Peninsula is 2.7 miles and takes about 18 minutes.")]}),
        ],
        "faq_title": "The island, answered",
        "faq": [("How far is the beach from the inn?", "A short bike ride. The Seawall runs along the Gulf side of the island, south of the inn."),
                ("Are the bikes free?", "Yes. Six cruisers with baskets and locks are free for guests, first come."),
                ("Do I need a car in Galveston?", "Not for the East End, The Strand or the nearest beach. You will want one for the west end of the island."),
                ("Is the Bolivar ferry free?", "Yes. It is free and it runs 24 hours a day. The crossing is 2.7 miles and takes about 18 minutes each way.")],
        "more": [("the-house.html", "The house and the 1900 Storm"), ("cruise-parking.html", "The night before a cruise")],
    },
    {
        "slug": "the-house", "nav": "house", "crumbs": [("Home", "index.html"), ("The house", "")],
        "title": "The House and the 1900 Storm | The Meraki Inn",
        "desc": "The story behind The Meraki Inn: an 1894 house in Galveston's East End, the 1900 Storm, the Seawall and the grade raising that lifted about 2,000 buildings.",
        "tone": "dawn", "when": "The year it was built", "clock": ("fixed", "1894", ""), "pic": "entry-hall", "tall": True, "article": True,
        "h1": "An 1894 house that was lifted off the ground and kept",
        "lede": "The house is older than the Seawall. In the grade raising it went up on jackscrews, like about 2,000 other buildings on the island.",
        "sections": [
            ("table", {"title": "What happened here, year by year?", "head": ["Year", "What happened"],
                       "rows": [("1874", "The Galveston Daily News calls the town the Oleander City in print."),
                                ("1894", "The house is built in the East End."),
                                ("September 8, 1900", "The 1900 Storm. At least 6,000 of the island's 44,000 residents die."),
                                ("1902 to 1904", "The first Seawall is built, about 3.3 miles long and 17 feet above mean low tide."),
                                ("1903 to 1911", "The grade raising. About 2,000 buildings across some 500 blocks are lifted on jackscrews while sand is pumped underneath."),
                                ("1975", "The East End Historic District is listed on the National Register of Historic Places."),
                                ("1976", "The district is named a National Historic Landmark."),
                                ("2014", "Celeste Arceneaux buys the house and starts two years of work."),
                                ("2016", "The Meraki Inn opens.")],
                       "caption": "The house and the inn are fictional. The storm, the Seawall, the grade raising and the district are real, with figures from the American Society of Civil Engineers and the National Park Service."}),
            ("lead", {"bg": "dark", "label": "The island", "title": "What was the grade raising?", "paras": [
                "<b>After the 1900 Storm, Galveston decided to stay and to get higher.</b> The Seawall went up first, from 1902 to 1904. Then, from 1903 to 1911, the city raised the ground behind it.",
                "About 2,000 buildings were lifted on jackscrews, a quarter turn at a time, while dredged sand was pumped underneath. Houses, churches and water lines all went up together, across some 500 city blocks.",
                "The Seawall has been extended ever since and now runs for more than 10 miles along the Gulf."]}),
            ("checks", {"label": "The house", "title": "What is original in the house?", "intro": "Celeste kept everything that could be kept. This list is part of the demo's story.",
                        "items": ["The heart pine floors, in every room", "The staircase, the newel post and the stained glass over the door", "The double gallery porches and their railings",
                                  "Pocket doors between the parlor and the dining room", "The brick cistern in the garden, now a planter", "The carriage house, which is now The Darkroom"], "pic": "exterior"}),
            ("rows", {"bg": "mist", "label": "The district", "title": "What is the East End Historic District?", "intro": "The inn's neighborhood: block after block of Victorian houses, a few minutes from the harbor.",
                      "items": [("About 150 acres", "Roughly bounded by Broadway, Market, 19th and 9th streets."),
                                ("More than 550 buildings", "Most are Victorian, with a few Greek Revival houses that are older still."),
                                ("A National Historic Landmark", "Listed on the National Register in 1975 and named a landmark in 1976.")]}),
        ],
        "faq_title": "The house, answered",
        "faq": [("How old is the inn?", "In this demo's story the house was built in 1894 and the inn opened in 2016."),
                ("Did the house survive the 1900 Storm?", "In this demo's story, yes. The inn is fictional. The storm, the Seawall and the grade raising are real, and the figures on this page come from the American Society of Civil Engineers and the National Park Service."),
                ("Is the East End a historic district?", "Yes. The East End Historic District covers about 150 acres and more than 550 buildings, and it has been a National Historic Landmark since 1976.")],
        "more": [("the-island.html", "What is near the inn"), ("hurricane-season.html", "Hurricane season and our refund policy")],
    },
    {
        "slug": "cruise-parking", "nav": "", "crumbs": [("Home", "index.html"), ("The island", "the-island.html"), ("The night before a cruise", "")],
        "title": "Stay the Night Before Your Galveston Cruise | The Meraki Inn",
        "desc": "Stay at The Meraki Inn the night before a Galveston cruise, leave your car in our gated lot and ride to the terminal. All four terminals are close by.",
        "tone": "morning", "when": "Embarkation morning", "clock": ("fixed", "10:30", "AM"), "pic": "exterior", "article": True,
        "h1": "Sleep on the island the night before your cruise",
        "lede": "Leave your car in our gated lot, eat breakfast on the gallery, and reach the terminal in a few minutes. Parking is $12 a day for guests, a sample rate for this demo.",
        "sections": [
            ("steps", {"label": "The morning", "title": "How does embarkation morning go?", "intro": "The same five steps for every guest who sails.",
                       "items": [("Coffee at 6:30", "It is on the hall table with the morning's baking."),
                                 ("Breakfast at 8", "Cooked to order on the gallery. If your arrival window is early, ask for a breakfast bag the night before."),
                                 ("A ride at your window", "Celeste drives guests to the terminal between 10:30 and noon. Your cruise line assigns your window, and it is on your boarding pass."),
                                 ("Your car stays behind the gate", "The lot is behind the house and the gate is locked at night."),
                                 ("A ride back", "Call when you are off the ship and we collect you from the terminal.")]}),
            ("table", {"bg": "mist", "title": "Which terminal does my ship leave from?", "head": ["Terminal", "Address", "Cruise lines"],
                       "rows": TERMINALS,
                       "caption": "From the Port of Galveston, checked October 2, 2026. Lines move between terminals, so go by your boarding pass."}),
            ("lead", {"bg": "dark", "label": "The night before", "title": "Why stay the night before a cruise?", "paras": [
                "<b>A ship does not wait for a late flight or a closed freeway.</b> Guests who drive in from Dallas, Austin or San Antonio the day before start the trip rested and already on the island.",
                "All four terminals are on Harborside Drive, on the harbor side of the island, a few minutes from the East End by car.",
                "The parking rate and the rides are part of this demo's story. On a live site this page would carry the inn's own package and price."]}),
        ],
        "faq_title": "Cruise parking, answered",
        "faq": [("How much is cruise parking at the inn?", "$12 a day for guests who stay the night before they sail. That is a sample rate for this demo."),
                ("How far is the inn from the cruise terminals?", "All four terminals are on Harborside Drive, on the harbor side of the island. The East End is a few minutes away by car."),
                ("Can I park at the inn if I am not staying?", "No. The lot is small, and it is kept for guests."),
                ("What time should I get to the terminal?", "Your cruise line assigns an arrival window and prints it on your boarding pass. Most of our guests leave the inn between 10:30 and noon.")],
        "more": [("breakfast.html", "Breakfast, and the early bag"), ("stay.html", "Rates and policies")],
    },
    {
        "slug": "dickens-on-the-strand", "nav": "", "crumbs": [("Home", "index.html"), ("The island", "the-island.html"), ("Dickens on The Strand", "")],
        "title": "Dickens on The Strand Weekend | The Meraki Inn",
        "desc": "Dickens on The Strand runs December 4 to 6, 2026 in Galveston. Hours, ticket prices and how the weekend works for guests of The Meraki Inn in the East End.",
        "tone": "golden", "when": "Fezziwig's Friday", "clock": ("fixed", "5:00", "PM"), "pic": "porch-night", "article": True,
        "h1": "Dickens on The Strand, close enough to walk home in costume",
        "lede": "The 53rd festival runs December 4 to 6, 2026. Friday evening is free, and it opens at 5.",
        "sections": [
            ("table", {"title": "When is Dickens on The Strand in 2026?", "head": ["Day", "Hours", "Admission"],
                       "rows": [("Friday, December 4", "5 PM to 9 PM", "Free. This is Fezziwig's Friday."),
                                ("Saturday, December 5", "10 AM to 9 PM", "Ticketed"),
                                ("Sunday, December 6", "Noon to 6 PM", "Ticketed")],
                       "caption": "From the Galveston Historical Foundation, which runs the festival. Checked October 2, 2026."}),
            ("rows", {"bg": "mist", "label": "Tickets", "title": "What do tickets cost?", "intro": "Prices from the Galveston Historical Foundation for 2026.",
                      "items": [("Adults", "$20 in advance."),
                                ("Youth, ages 7 to 12", "$13 in advance."),
                                ("Children 6 and under", "Free."),
                                ("After November 20", "Prices go up by $5."),
                                ("In Victorian costume", "Half off admission, at the gate only.")]}),
            ("lead", {"bg": "dark", "label": "At the inn", "title": "How does the weekend work at the inn?", "paras": [
                "<b>The Strand is about half a mile from our porch, so guests walk there and walk back.</b> No one has to find parking downtown.",
                "We ask for three nights that weekend, Thursday to Sunday. There is a trunk of shawls and top hats in the hall for anyone who arrived without a costume, and hot cider on the porch on Friday before the gates open.",
                "The three night stay, the trunk and the cider are part of this demo's story. The festival, its dates and its prices are real."]}),
        ],
        "faq_title": "Dickens weekend, answered",
        "faq": [("When is Dickens on The Strand in 2026?", "December 4 to 6, 2026. It is the 53rd year of the festival, which the Galveston Historical Foundation runs on The Strand."),
                ("Is Friday night free?", "Yes. Fezziwig's Friday runs from 5 PM to 9 PM on December 4 and admission is free."),
                ("Can I walk to the festival from the inn?", "Yes. The Strand is about half a mile from the East End, and most guests walk there and back."),
                ("Do I need a costume?", "No. Victorian dress does get half off admission at the gate, according to the Galveston Historical Foundation.")],
        "more": [("the-island.html", "What else is near the inn"), ("rooms.html", "See the rooms")],
    },
    {
        "slug": "hurricane-season", "nav": "", "crumbs": [("Home", "index.html"), ("The island", "the-island.html"), ("Hurricane season", "")],
        "title": "Hurricane Season and Our Refund Policy | The Meraki Inn",
        "desc": "Hurricane season in Galveston runs June 1 to November 30. If a hurricane warning covers the island during your dates, The Meraki Inn refunds the stay in full.",
        "tone": "morning", "when": "The morning advisory", "clock": ("fixed", "10:00", "AM"), "pic": "beach-sunrise", "article": True,
        "h1": "If a hurricane warning covers the island, your stay is refunded",
        "lede": "The National Hurricane Center posts a full advisory every six hours: at 4 and 10, morning and evening, Central daylight time. From June through November we read every one.",
        "sections": [
            ("table", {"title": "What is the difference between a watch and a warning?", "head": ["What is issued", "What it means", "What we do"],
                       "rows": [("Hurricane watch", "Hurricane conditions are possible in the area. A watch usually comes about 48 hours before tropical storm force winds are expected.", "You can move your dates at no charge."),
                                ("Hurricane warning", "Hurricane conditions are expected in the area. A warning usually comes about 36 hours ahead.", "We refund your stay in full."),
                                ("Tropical storm warning", "Tropical storm conditions are expected in the area.", "You can move your dates at no charge."),
                                ("Evacuation order", "Local officials tell people to leave the island.", "The inn closes and every booking is refunded.")],
                       "caption": "Definitions from the National Weather Service. The refund policy is a sample for this demo."}),
            ("rows", {"bg": "mist", "label": "The forecast", "title": "How do we keep you informed?", "intro": "The policy is tied to the official watch and warning, so no one has to guess.",
                      "items": [("Season dates", "The Atlantic hurricane season runs from June 1 to November 30."),
                                ("Advisories every six hours", "At 4 AM, 10 AM, 4 PM and 10 PM Central daylight time. When a coastal watch or warning is in effect, shorter updates come every three hours in between."),
                                ("A message from us", "If a watch is posted for Galveston, we email every guest booked that week the same day."),
                                ("Your call, with time to make it", "A watch gives about two days of notice. You never have to decide before the forecast does.")]}),
            ("lead", {"bg": "dark", "label": "The island", "title": "Is Galveston a good idea in hurricane season?", "paras": [
                "<b>Most summer and fall days on the island are ordinary beach days.</b> The water is warm, the rates are lower after Labor Day, and the porch is at its best in October.",
                "The Seawall and the grade raising were built for the other days. A forecast gives days of notice, and our policy is written so that a storm never costs you the room.",
                "The policy covers your stay with us. It does not cover a flight, a cruise or a rental car, so travel insurance can still be worth having."]}),
        ],
        "faq_title": "Storm season, answered",
        "faq": [("When is hurricane season in Galveston?", "June 1 to November 30."),
                ("Do I get my money back if a hurricane is forecast?", "If a hurricane warning is issued for Galveston during your dates, we refund the stay in full. If a hurricane watch is posted, you can move your dates at no charge."),
                ("What about a tropical storm?", "A tropical storm warning for the island lets you move your dates at no charge."),
                ("Do I still need travel insurance?", "Our policy covers your room. It does not cover a flight, a cruise or a rental car, so that is a decision for you and your insurer.")],
        "more": [("stay.html", "Rates and policies"), ("the-house.html", "The house and the 1900 Storm")],
    },
    {
        "slug": "about", "nav": "", "crumbs": [("Home", "index.html"), ("Who keeps the inn", "")],
        "title": "Who Keeps the Inn | The Meraki Inn, Galveston",
        "desc": "Meet the people behind The Meraki Inn in Galveston and what the Greek word meraki means: doing something with soul, creativity and love put into the work.",
        "tone": "dawn", "when": "Coffee is out", "clock": ("fixed", "6:30", "AM"), "pic": "innkeeper",
        "h1": "Kept with meraki, by two people who are here every day",
        "lede": "Meraki is a Greek word for doing something with soul, creativity and love, so that a piece of you ends up in the work.",
        "sections": [
            ("lead", {"label": "The name", "title": "What does meraki mean?", "paras": [
                "<b>It is the word for the care you can taste in a meal or see in a room.</b> We took it as a rule for the house.",
                "Each of the five rooms is furnished around one craft, made by hand in Texas: a loom, a kiln, a press, a bindery, a darkroom. Breakfast is cooked to order and eaten on the gallery. The floors are the heart pine the house was built with.",
                "It also means that a person answers the phone, and that the person knows the rooms."]}),
            ("people", {"bg": "dark"}),
            ("rows", {"bg": "mist", "label": "Your details", "title": "How do we handle your details?", "intro": "An inn hears a lot about its guests. Here is what we ask for and what we do with it.",
                      "items": [("The form asks for five things", "Your arrival day, the number of nights, a room, your name and your email. Nothing else."),
                                ("Cards are taken by phone", "You read the number to Celeste and she keys it into the card terminal. It is never written down, emailed or sent through this website."),
                                ("We never ask for a gift card, a wire or a payment app", "If a message asks you to pay for a room that way, it is not from us. Call the inn."),
                                ("The chat is an AI, and it says so", "It answers from these pages and can fill in your dates and room on the request form. It never asks for a name, an email or a card."),
                                ("You can ask what we hold", 'Call and we will tell you what is in your booking record. The <a href="privacy.html">privacy page</a> has the rest.')]}),
        ],
        "faq_title": "The inn, answered",
        "faq": [("Who owns The Meraki Inn?", "Celeste Arceneaux, who is also the innkeeper. She and Isadora Fontenot are fictional people, written for this demo."),
                ("How do you pronounce meraki?", "meh RAH kee, with the weight on the middle."),
                ("How do I pay for my room?", "By card, over the phone, once we have confirmed your dates. We never take a card number through the website, the chat or by email."),
                ("Is the chat a person?", "No. Ask the inn is an AI assistant. It answers from the pages of this website and can fill in the date request form for you. On this demo, nothing it fills in is sent anywhere.")],
        "more": [("breakfast.html", "Breakfast on the gallery"), ("the-house.html", "The house")],
    },
    {
        "slug": "stay", "nav": "stay", "crumbs": [("Home", "index.html"), ("Rates and policies", "")],
        "title": "Rates and Policies | The Meraki Inn, Galveston",
        "desc": "Room rates and policies at The Meraki Inn in Galveston: five rooms from $189 to $289 with breakfast, check in from 3 PM, and what the hotel occupancy tax adds.",
        "tone": "noon", "when": "Check in", "clock": ("fixed", "3:00", "PM"), "pic": "porch-golden",
        "h1": "Rates, tax and the house rules, in plain words",
        "lede": "Five rooms from $189 to $289 a night, breakfast included. Check in is from 3 PM and check out is by 11 AM.",
        "sections": [
            ("rates", {}),
            ("lead", {"bg": "dark", "label": "Tax", "title": "What does tax add to a room in Galveston?", "paras": [
                "<b>Hotel occupancy tax adds 15 percent.</b> The State of Texas charges 6 percent of the cost of a room and the City of Galveston charges 9 percent.",
                "Two nights in The Loom at $249 come to $498. Tax adds $74.70, for a total of $572.70.",
                "Nothing else is added. There is no resort fee and no charge for parking, bikes, wifi or breakfast."]}),
            ("rows", {"label": "The house rules", "title": "What are the policies?", "intro": "These are samples for this demo, written the way a live inn would write them.",
                      "items": [("Check in and check out", "Check in from 3 PM to 8 PM. Check out by 11 AM. Call if you will be late and we will leave the porch light on."),
                                ("Minimum stay", "Two nights on Friday and Saturday. Three nights for Dickens on The Strand and both Mardi Gras weekends."),
                                ("Deposit and payment", "One night is charged when we confirm your dates, by card, over the phone. The rest is charged at check in."),
                                ("Cancelling", "Cancel seven days ahead for a full refund. For festival weekends it is fourteen days."),
                                ("Storms", 'A hurricane warning for Galveston during your dates means a full refund. See <a href="hurricane-season.html">hurricane season</a>.'),
                                ("Children", "Children 12 and older are welcome in the house. Children of any age are welcome in The Darkroom."),
                                ("Pets and smoking", "No pets, and no smoking anywhere on the property."),
                                ("Parking", "Free for guests, in the gated lot behind the house.")]}),
        ],
        "faq_title": "Rates and policies, answered",
        "faq": [("What time is check in at the inn?", "From 3 PM to 8 PM. Check out is by 11 AM."),
                ("Is there a minimum stay?", "Two nights on Friday and Saturday, and three nights for Dickens on The Strand and both Mardi Gras weekends."),
                ("What is the cancellation policy?", "Cancel seven days ahead for a full refund, or fourteen days ahead for festival weekends. A hurricane warning for Galveston during your dates always means a full refund."),
                ("How much is the tax on a room in Galveston?", "15 percent. The state hotel occupancy tax is 6 percent and the City of Galveston adds 9 percent."),
                ("Do you take a deposit?", "Yes. One night, taken by card over the phone when we confirm your dates.")],
        "more": [("rooms.html", "See the rooms"), ("about.html", "How we handle your details")],
    },
]

PRIVACY = [
    ("What does this website collect?", [
        "The date request form asks for five things: your arrival day, the number of nights, a room, your name and your email. That is all it asks for.",
        "This is a demo site, so the form sends nothing anywhere. On a live site, those five details would go to the innkeeper and to no one else."]),
    ("What happens to what I type in the chat?", [
        "The Ask the inn chat is an AI assistant. What you type is sent through this website's server to Anthropic, the AI provider that writes the replies, and is handled under its terms. This website does not store it.",
        "The conversation is kept in your browser tab so it can follow you from page to page, and it is gone when you close the tab. The server keeps your internet address in memory for up to a minute, only to stop one visitor from running up the cost.",
        "The assistant never asks for your name, your email, your phone number or a card. It can fill in the arrival day, the nights and the room on the date request form, and nothing else. If a message looks like a card number, it is stopped before it is sent to the provider."]),
    ("How is a card taken?", [
        "By phone, once your dates are confirmed. You read the number to the innkeeper and it is keyed into the card terminal while you are on the line.",
        "A card number is never asked for on this website, by email or by text, and it is never written down."]),
    ("What will the inn never ask for?", [
        "Payment by gift card, wire transfer or a payment app. A photo of your card or your identification. A password to anything.",
        f"If a message asks for any of those in our name, it is not from us. Call the inn at {PHONE}."]),
    ("What does the inn keep, and for how long?", [
        "A booking record: your name, email, phone number, dates, room and anything you told us about breakfast. On a live site it would be kept for as long as tax law requires and then deleted.",
        "We do not sell guest details and we do not share them, except with the card processor that handles the payment."]),
    ("Does the website use cookies or tracking?", [
        "This demo sets no cookies and loads no advertising or analytics scripts. It loads its typefaces from Google Fonts. The chat keeps its conversation in your browser tab's own storage until the tab is closed.",
        "Today's sunrise and sunset are worked out in your own browser from the date. The page does not ask for your location."]),
    ("How do I ask what you hold about me?", [
        f"Call {PHONE} and ask. We will tell you what is in your booking record and correct or delete it where the law allows."]),
]
