"""Page copy for the Keelhouse demo. Keelhouse is fictional; places are real.
House rules for this copy: no dashes as punctuation, plain first person plural, specific over general."""

REVIEWS = [
    ("They traced a breaker that kept tripping back to the water heater in one visit. Two other companies had blamed each other for a month.", "Karen M.", "Dublin"),
    ("Showed up inside the window, put down runners without being asked, and sent photos of the new lines before he left.", "Tom R.", "Westerville"),
    ("The price on the tablet was the price on the invoice. That's all I wanted.", "Angela P.", "Grove City"),
    ("Our 1920s house had pipes nobody wanted to touch. They explained every step and finished a day early.", "Chris D.", "Columbus"),
]

HOME_FAQ = [
    ("Do you charge to come out and diagnose?", "Yes. Diagnostic visits start at $95 for plumbing, $110 for electrical and $120 for heating and cooling, and the fee comes off the bill if you go ahead with the repair."),
    ("Can one visit cover a plumbing and an electrical problem?", "Yes. Tell us both when you book and we send a tech licensed for each, or schedule them back to back the same day."),
    ("Do you pull permits in Columbus and the suburbs?", "Yes. When a panel upgrade, water heater replacement or furnace replacement needs a permit, we file it with the city and schedule the inspection."),
    ("Are you licensed and insured in Ohio?", "Yes. Our master plumber, master electrician and HVAC techs hold Ohio licenses, and every tech carries proof on site."),
    ("How fast can you get to my house?", "Most weekday calls get a same day window. Each city page lists typical arrival times from our Columbus dispatch."),
]

SERVICES_FAQ = [
    ("How does your pricing work?", "Every job starts with a diagnostic visit. After the tech finds the cause, you get a written price for the fix. If you go ahead, the visit fee is credited toward it."),
    ("Do you offer maintenance plans?", "Yes. The Keelhouse Care plan covers a fall furnace tune up, a spring AC tune up, a water heater flush and a whole home electrical safety check each year, with priority scheduling."),
    ("What counts as an emergency?", "Active water leaks, no heat in cold weather, sparking or burning smells from outlets or the panel, and sewer backups. Call the emergency line any hour for those."),
    ("Do you work on rental properties?", "Yes. We work with landlords and property managers across the metro, and we can coordinate access with tenants directly."),
]

AREAS_FAQ = [
    ("Which areas do you serve?", "Columbus, Dublin, Westerville and Grove City, plus Hilliard, Upper Arlington, Worthington, Gahanna and Powell. If you're close to any of those, call and ask."),
    ("Do you charge extra for travel?", "No. The diagnostic visit price is the same anywhere in our service area."),
    ("Who handles permits in each city?", "We do. Each city runs its own permit office and inspection schedule, and we file and schedule with whichever one covers your address."),
]

HOW_FAQ = [
    ("Do I need to be home during the visit?", "For the diagnosis, yes, or someone who can approve the price. For longer jobs, many customers leave us a code and we text updates and photos through the day."),
    ("What does the warranty cover?", "One year on labor for repairs. Installs carry our labor warranty plus the manufacturer's equipment warranty, which we register for you."),
    ("Are your techs employees or subcontractors?", "Employees. Every tech on a Keelhouse truck works for us, is background checked, and is trained on how we run a visit."),
    ("How do you handle surprises once work starts?", "We stop and show you. If a job changes once a wall or floor is open, you see photos and a revised written price before we continue."),
]

SERVICE_PAGES = {
    "plumbing": {
        "title": "Plumber in Columbus, OH | Keelhouse",
        "desc": "Licensed plumbing for Columbus, Dublin, Westerville and Grove City homes: leaks, drains, water heaters, sump pumps and repipes. Visits from $95.",
        "h1": 'Water where you want it. <span class="accent">Nowhere else.</span>',
        "lede": "Leaks, slow drains, water heaters and old supply lines, fixed by a licensed plumbing crew. Diagnostic visits from $95, credited toward the repair.",
        "img_alt": "A plumber fitting new copper water lines in a basement",
        "summary": "From a dripping shutoff to a whole house repipe. Much of Central Ohio's older housing still runs on galvanized supply lines, and the hard water here is rough on water heaters, so those are the jobs we do most.",
        "price_title": "Plumbing jobs, priced up front.",
        "prices": [
            ("Diagnostic visit", "A licensed plumber finds the cause and quotes the fix", "$95"),
            ("Drain clearing", "Kitchen, bath and laundry lines, camera inspection if needed", "From $189"),
            ("Faucet and fixture installs", "Faucets, toilets, disposals and shutoff valves", "From $225"),
            ("Tank water heater replacement", "40 or 50 gallon gas or electric, haul away included", "From $1,650"),
            ("Tankless water heater install", "Includes venting, gas line and descaling kit", "From $3,900"),
            ("Sump pump replacement", "Primary pump, check valve and a test run", "From $650"),
            ("Whole house repipe", "Galvanized to copper and PEX, with patch plan", "Free estimate"),
        ],
        "signs_lead": "If one of these sounds familiar, a diagnostic visit usually finds the cause in under an hour.",
        "signs": ["Rusty or brown water when a tap first opens", "Water pressure that dropped over the years", "A water heater older than ten years, or one that rumbles", "Drains that gurgle or back up into another fixture", "A sump pump that runs constantly, or not at all", "A water bill that jumped without a change in use"],
        "project": "galvanized-repipe-westerville-oh",
        "preset": "leak",
        "faq": [
            ("How much does a water heater replacement cost in Columbus?", "Most tank replacements land between $1,650 and $2,400 depending on size, fuel and venting. Tankless installs start around $3,900. You get the exact price in writing first."),
            ("Should I switch to a tankless water heater?", "It makes sense for bigger households and homes with room for the venting. With Central Ohio's hard water, plan on a yearly descale. The plumber will walk you through both options on site."),
            ("How do I know if I have galvanized pipes?", "Scratch an exposed pipe in the basement with a key. Galvanized steel is dull gray and a magnet sticks to it. Copper shows a bright penny color. If you're unsure, the plumber can check during any visit."),
            ("Do you handle sewer line problems?", "Yes. We start with a camera inspection so you can see the problem, then quote a repair or a lining option before anything is dug up."),
        ],
    },
    "heating-cooling": {
        "title": "Furnace and AC Repair in Columbus, OH | Keelhouse",
        "desc": "Furnace and AC repair, tune ups and heat pump installs for Columbus, Dublin, Westerville and Grove City. Visits from $120, written prices, 24/7 emergency line.",
        "h1": 'Heat that comes on. <span class="accent">Air that stays cold.</span>',
        "lede": "Furnace, AC and heat pump repair, tune ups and installs. Diagnostic visits from $120, credited toward the repair.",
        "img_alt": "An HVAC technician checking a gas furnace with pressure gauges",
        "summary": "Ohio asks a lot of a heating system in January and a lot of an AC in July. We keep both running, and when it's time to replace, we size the new system to your house instead of guessing from the old one.",
        "price_title": "Heating and cooling jobs, priced up front.",
        "prices": [
            ("Diagnostic visit", "An EPA 608 certified tech finds the cause and quotes the fix", "$120"),
            ("Furnace tune up", "Burner, ignitor, flame sensor, filter and safety checks", "$129"),
            ("AC tune up", "Coil cleaning, refrigerant check and electrical test", "$129"),
            ("Furnace repair", "Ignitors, inducer motors, control boards, blower motors", "From $240"),
            ("AC repair", "Capacitors, contactors, fan motors and refrigerant leaks", "From $260"),
            ("Smart thermostat install", "Wiring, setup and a walkthrough on your phone", "From $195"),
            ("Heat pump or AC replacement", "Load calculation, permit and haul away included", "Free estimate"),
        ],
        "signs_lead": "If one of these sounds familiar, a diagnostic visit usually finds the cause in under an hour.",
        "signs": ["Furnace runs but the house won't warm up", "Breaker trips when the AC kicks on", "Water pooling around the furnace or air handler", "Energy bill jumped without a change in use", "One room always hotter or colder than the rest", "System is 15 or more years old"],
        "project": "heat-pump-install-grove-city-oh",
        "preset": "no-heat",
        "faq": [
            ("How much does a furnace repair cost in Columbus?", "The diagnostic visit is $120 and comes off the bill if you go ahead. Common repairs like an ignitor or flame sensor run $240 to $450. You get the exact price before any work starts."),
            ("Should I repair or replace my furnace?", "If it's under 12 years old and the repair is less than a third of the cost of a new system, repair usually wins. The tech walks you through both numbers on site."),
            ("Do heat pumps work in an Ohio winter?", "Today's cold climate heat pumps heat well into the single digits. Many Columbus homes pair one with the existing gas furnace as a backup for the coldest days, which is called a dual fuel setup."),
            ("How often should I change my furnace filter?", "Every one to three months for a standard one inch filter, more often with pets. Thicker media filters can go six months or more."),
        ],
    },
    "electrical": {
        "title": "Electrician in Columbus, OH | Keelhouse",
        "desc": "Licensed electrical work for Columbus, Dublin, Westerville and Grove City homes: panel upgrades, EV chargers, lighting and surge protection. Visits from $110.",
        "h1": 'Power you never <span class="accent">have to think about.</span>',
        "lede": "Panels, circuits, lighting and EV chargers, done to code by a licensed electrician and inspected when the city requires it. Diagnostic visits from $110.",
        "img_alt": "An electrician working inside a residential breaker panel",
        "summary": "A lot of Central Ohio homes were wired for less than they run today. Heat pumps, EV chargers and kitchen remodels all ask the panel for more. We find out what yours can carry, then upgrade only what you need.",
        "price_title": "Electrical jobs, priced up front.",
        "prices": [
            ("Diagnostic visit", "A licensed electrician finds the cause and quotes the fix", "$110"),
            ("Outlet or switch repair", "Including GFCI and AFCI protection where code calls for it", "From $165"),
            ("Light fixture install", "Ceiling fixtures, fans and under cabinet lighting", "From $175"),
            ("Whole home surge protector", "Installed at the panel, protects every circuit", "From $395"),
            ("EV charger install", "Level 2 charger, dedicated circuit and permit", "From $850"),
            ("200 amp panel upgrade", "Permit, utility coordination and inspection included", "From $2,400"),
            ("Whole home rewiring", "Knob and tube or aluminum branch circuits", "Free estimate"),
        ],
        "signs_lead": "Some of these are urgent. If you smell burning or see scorch marks, turn the circuit off and call the emergency line.",
        "signs": ["Breakers that trip when two things run at once", "Lights that dim when the AC or a big appliance starts", "Outlets that feel warm or have scorch marks", "Two prong outlets throughout an older house", "Planning an EV charger, heat pump or hot tub", "A panel from the 1980s or earlier, or a Federal Pacific panel"],
        "project": "panel-upgrade-dublin-oh",
        "preset": "electrical",
        "faq": [
            ("How much does a panel upgrade cost in Columbus?", "Most 100 to 200 amp upgrades run $2,400 to $3,800, including the permit, utility coordination and inspection. You get the exact price in writing first."),
            ("Do I need a panel upgrade for an EV charger?", "Not always. A load calculation tells us whether your panel has room. Many homes can add a Level 2 charger on the existing panel, sometimes with a smart load management device."),
            ("Will I lose power during a panel upgrade?", "For part of one day. We coordinate the disconnect and reconnect with the utility and schedule around your plans."),
            ("Are two prong outlets dangerous?", "They aren't grounded, which matters for computers, TVs and anything with a three prong plug. We can ground them or add GFCI protection to meet code."),
        ],
    },
}

CITY_PAGES = {
    "columbus-oh": {
        "title": "Home Services in Columbus, OH | Keelhouse",
        "desc": "Based in Columbus. Plumbing, heating and electrical for German Village, Clintonville, Short North and Victorian Village homes, with same day windows.",
        "h1": 'Plumbing, heating and electrical in <span class="accent">Columbus.</span>',
        "lede": "Our shop and dispatch are here, so Columbus gets the shortest arrival windows we offer.",
        "img_alt": "Brick Italianate homes along a brick street in a historic Columbus neighborhood",
        "intro_h": "Old houses, new demands.",
        "intro": ["Columbus has some of the oldest housing in Ohio. German Village and Victorian Village still have homes from the 1800s, and much of Clintonville went up between the 1910s and the 1950s.",
                  "That means galvanized pipe, cast iron drains, small electrical panels and boilers that have been patched for decades. We work on those houses every day, and we know which upgrades make sense in a house that old and which ones don't."],
        "arrival": "Same day, 2 hour window",
        "dispatch": "Our Columbus shop",
        "most": "Galvanized pipe replacement",
        "zips": ["43201", "43202", "43206", "43214", "43215"],
        "hoods_lead": "A sample of the Columbus neighborhoods we're in most weeks.",
        "hoods": [
            ("German Village", "Brick cottages from the 1800s on narrow lots and brick streets. Tight basements, original drain lines and lots of careful work in finished spaces."),
            ("Clintonville", "Homes from the 1910s to the 1950s with mature trees and older sewer laterals. Root intrusion and galvanized supply lines are common calls."),
            ("Short North", "Rehabbed historic buildings next to new condos. Mixed wiring generations, tankless water heaters and condo association rules."),
            ("Victorian Village", "Large Victorian homes, many converted to doubles. Boilers, knob and tube wiring and multiple meters."),
        ],
        "jobs": [
            ("Plumbing", "Galvanized to copper and PEX", "Rusty water and low pressure in pre war homes, replaced in stages to keep the house usable."),
            ("Electrical", "Knob and tube replacement", "Old cloth wiring that insurers flag, rewired with as little plaster damage as we can manage."),
            ("Heating", "Boiler service and repair", "Hot water and steam boilers in older homes, kept running or replaced with a high efficiency unit."),
        ],
        "review": ("Our 1920s house had pipes nobody wanted to touch. They explained every step and finished a day early.", "Chris D.", "Clintonville"),
        "faq": [
            ("Do you work on historic homes in German Village?", "Yes, often. We plan around finished plaster, tight basements and exterior rules, and we'll talk through options that keep the character of the house."),
            ("Can you replace galvanized pipe without opening every wall?", "Usually most of it. We run new lines through basements, closets and chases, and plan any wall openings with you before we start."),
            ("How fast can you get to a Columbus address?", "Columbus calls usually get a same day, two hour window because our dispatch is here."),
        ],
        "also": "Bexley, Grandview Heights and Upper Arlington",
    },
    "dublin-oh": {
        "title": "Plumbing, HVAC and Electrical in Dublin, OH | Keelhouse",
        "desc": "Plumbing, heating and electrical for Dublin, Ohio homes in Historic Dublin, Bridge Park, Muirfield Village and Ballantrae. Same day windows, written prices.",
        "h1": 'Plumbing, heating and electrical in <span class="accent">Dublin, Ohio.</span>',
        "lede": "From the stone buildings in Historic Dublin to the newer builds around Bridge Park and Muirfield, Dublin mixes old plumbing with new systems.",
        "img_alt": "Historic stone storefront buildings along a riverside street",
        "intro_h": "Bigger homes, bigger systems.",
        "intro": ["Much of Dublin was built from the 1970s on, and a lot of it is large homes with two furnaces, finished basements and big electrical loads. Those systems are now at the age where they need replacing, often all within a few years of each other.",
                  "We help Dublin homeowners plan that, one system at a time, so a furnace, a water heater and a panel don't all fail in the same winter."],
        "arrival": "Same day, 2 to 4 hour window",
        "dispatch": "Columbus shop, about 20 minutes",
        "most": "Panel upgrades for EV chargers",
        "zips": ["43016", "43017"],
        "hoods_lead": "A sample of the Dublin neighborhoods we're in most weeks.",
        "hoods": [
            ("Historic Dublin", "Older stone and frame buildings near the Scioto River. Careful work in tight spaces and original plumbing."),
            ("Bridge Park", "Newer condos and townhomes. Tankless water heaters, compact mechanical closets and association rules on access."),
            ("Muirfield Village", "Large homes from the 1970s through the 1990s. Two furnace setups, original panels and big water heaters coming due."),
            ("Ballantrae", "Homes from the 2000s. First generation high efficiency furnaces and the first round of water heater replacements."),
        ],
        "jobs": [
            ("Electrical", "Panel upgrades for EVs and heat pumps", "Original panels running out of room as Dublin homes add chargers and electrify."),
            ("Plumbing", "Water heater replacements", "Big tank heaters from the 1990s and 2000s, replaced or switched to tankless."),
            ("Heating", "Two zone system replacements", "Upstairs and downstairs systems replaced together, sized to the house as it is today."),
        ],
        "review": ("They traced a breaker that kept tripping back to the water heater in one visit. Two other companies had blamed each other for a month.", "Karen M.", "Muirfield Village"),
        "faq": [
            ("How quickly can you get to Dublin?", "Most weekday calls get a same day window. Dublin is about 20 minutes from our Columbus dispatch, so emergency calls usually arrive within 90 minutes."),
            ("Do you file permits with the City of Dublin?", "Yes. When a panel upgrade, water heater replacement or furnace replacement needs a permit, we file it and schedule the inspection."),
            ("Do you work in Muirfield Village and other HOA neighborhoods?", "Yes. We work around HOA rules on vans, hours and where outdoor equipment can go, and we can send any paperwork your association asks for."),
        ],
        "also": "Hilliard, Powell and Upper Arlington",
    },
    "westerville-oh": {
        "title": "Home Services in Westerville, OH | Keelhouse",
        "desc": "Plumbing, heating and electrical for Westerville, Ohio homes in Uptown, near Alum Creek and in Genoa Township. Same day windows, written prices.",
        "h1": 'Plumbing, heating and electrical in <span class="accent">Westerville.</span>',
        "lede": "Older homes around Uptown and Otterbein, newer neighborhoods out toward Alum Creek, and one crew that works on both.",
        "img_alt": "A brick main street with Victorian storefronts at golden hour",
        "intro_h": "Two kinds of Westerville house.",
        "intro": ["Near Uptown and Otterbein University, Westerville has early 1900s homes with galvanized pipe and older wiring. Out toward Alum Creek and Genoa Township, it's subdivisions from the 1990s on, with their own set of aging systems.",
                  "We work on both, and we'll tell you which upgrades are worth it for the house you have, and which ones can wait."],
        "arrival": "Same day, 2 to 4 hour window",
        "dispatch": "Columbus shop, about 25 minutes",
        "most": "Galvanized repipes near Uptown",
        "zips": ["43081", "43082"],
        "hoods_lead": "A sample of the Westerville neighborhoods we're in most weeks.",
        "hoods": [
            ("Uptown Westerville", "Homes from the late 1800s and early 1900s near the historic district. Galvanized pipe, old drains and small panels."),
            ("Near Otterbein", "Older homes, many now rentals. We work with landlords on tenant access and code updates."),
            ("Alum Creek", "Subdivisions from the 1990s and 2000s. First generation high efficiency furnaces and sump pumps that work hard in spring."),
            ("Genoa Township", "Newer, larger homes on Westerville addresses. Two story systems, finished basements and irrigation lines."),
        ],
        "jobs": [
            ("Plumbing", "Galvanized water line replacement", "Low pressure and rusty water in pre war homes near Uptown."),
            ("Plumbing", "Sump pump replacements", "Pumps that fail in spring storms, replaced with battery backup where it makes sense."),
            ("Heating", "Furnace and AC tune ups", "Twice a year visits for homes on the Keelhouse Care plan."),
        ],
        "review": ("Showed up inside the window, put down runners without being asked, and sent photos of the new lines before he left.", "Tom R.", "Uptown Westerville"),
        "faq": [
            ("How quickly can you get to Westerville?", "Most weekday calls get a same day window. Westerville is about 25 minutes from our Columbus dispatch."),
            ("Do you work on rental homes near Otterbein?", "Yes. We work with landlords and property managers, coordinate access with tenants, and send photos and invoices to the owner."),
            ("Should I add a battery backup to my sump pump?", "If your basement is finished or you've had water before, yes. A backup keeps pumping when a spring storm knocks the power out."),
        ],
        "also": "Worthington, Gahanna and Powell",
    },
    "grove-city-oh": {
        "title": "Home Services in Grove City, OH | Keelhouse",
        "desc": "Plumbing, heating and electrical for Grove City, Ohio homes in Town Center, Beulah Park and Pinnacle. Same day windows, written prices.",
        "h1": 'Plumbing, heating and electrical in <span class="accent">Grove City.</span>',
        "lede": "Ranch homes from the 1960s and 70s, newer neighborhoods like Beulah Park, and a crew that's twenty minutes away.",
        "img_alt": "A tree lined suburban street of brick homes at golden hour",
        "intro_h": "Ranch homes ready for their second systems.",
        "intro": ["A lot of Grove City is single story brick ranches from the 1960s and 1970s. Most are on their second or third furnace and water heater, and many still have the original electrical panel.",
                  "Newer neighborhoods like Beulah Park and Pinnacle are just reaching their first round of replacements. We help both plan ahead, so the replacement happens on your schedule instead of the system's."],
        "arrival": "Same day, 2 to 4 hour window",
        "dispatch": "Columbus shop, about 20 minutes",
        "most": "Heat pump and furnace replacements",
        "zips": ["43123"],
        "hoods_lead": "A sample of the Grove City neighborhoods we're in most weeks.",
        "hoods": [
            ("Town Center", "Older homes near the historic downtown. Original drains, small panels and gas lines that need checking before new appliances."),
            ("Beulah Park", "New construction on the site of the old racetrack. Warranty questions, smart thermostats and first water heater service."),
            ("Pinnacle", "Homes from the 2000s around the golf club. First generation high efficiency systems coming due."),
            ("Ranch neighborhoods", "Brick ranches from the 1960s and 70s. Slab and crawlspace plumbing, and HVAC sized for a very different house."),
        ],
        "jobs": [
            ("Heating", "Dual fuel heat pump installs", "A heat pump for most of the year, with the gas furnace kept for the coldest days."),
            ("Electrical", "Panel replacements in ranch homes", "Original panels replaced, often alongside an HVAC or kitchen upgrade."),
            ("Plumbing", "Water heater replacements", "Tank swaps with code updates to venting and expansion tanks."),
        ],
        "review": ("The price on the tablet was the price on the invoice. That's all I wanted.", "Angela P.", "Grove City"),
        "faq": [
            ("How quickly can you get to Grove City?", "Most weekday calls get a same day window. Grove City is about 20 minutes from our Columbus dispatch."),
            ("Is a heat pump a good fit for a Grove City ranch?", "Often, yes. Single story ranches are easy to heat and cool evenly, and a dual fuel setup keeps the gas furnace for the coldest days."),
            ("Do you service new homes in Beulah Park?", "Yes. We can do first year service and water heater flushes, and help sort out what the builder's warranty covers."),
        ],
        "also": "Hilliard, Urbancrest and the south side of Columbus",
    },
}

PROJECT_PAGES = {
    "panel-upgrade-dublin-oh": {
        "summary": "A 1990s Muirfield Village home with its original 150 amp panel needed room for an EV charger and a heat pump. We upgraded to 200 amps in one day, with the permit and inspection handled.",
        "desc": "A 200 amp panel upgrade in a 1990s Muirfield Village home in Dublin, Ohio, to make room for an EV charger and a heat pump.",
        "img_alt": "A newly installed 200 amp residential breaker panel in a basement",
        "caption": "The new 200 amp panel, with room left for future circuits. Photo for this demo.",
        "note": "A Keelhouse electrical project in Dublin, Ohio. Written up so neighbors planning the same upgrade know what's involved.",
        "meta": [("Trade", "Electrical"), ("Neighborhood", "Muirfield Village"), ("Home built", "1994"), ("Time on site", "1 day"), ("Permit", "Filed and inspected")],
        "sections": [
            ("The problem", ["The homeowners had ordered an electric car and were planning to replace their aging AC with a heat pump. A load calculation showed the original 150 amp panel couldn't carry both on top of a house this size.",
                             "Two breakers were also showing heat discoloration, and the panel had no space left for new circuits."]),
            ("What we did", ["We filed the permit with the City of Dublin and coordinated the disconnect and reconnect with AEP Ohio. On install day, power was off from 8 AM to about 3 PM.",
                             "We replaced the panel with a 200 amp unit, moved every circuit over with new labels, added a whole home surge protector, and ran a dedicated 50 amp circuit to the garage for the charger. The city inspection passed the next morning."]),
            ("The result", ["The house now has room for the charger, the heat pump and a future generator inlet. The homeowners got a labeled panel map and photos of every circuit in their home file."]),
        ],
        "preset": "electrical",
        "date": "2026-08-14",
    },
    "galvanized-repipe-westerville-oh": {
        "summary": "A 1920s home near Uptown Westerville had rusty water and almost no pressure upstairs. We replaced the galvanized supply lines with copper mains and PEX branches over three days, with the family still living there.",
        "desc": "A galvanized water line replacement in a 1920s home near Uptown Westerville, Ohio, done over three days with the family at home.",
        "img_alt": "New PEX and copper water lines run along basement joists, with removed galvanized pipe on a drop cloth",
        "caption": "New lines along the basement joists, with a section of the old galvanized pipe we pulled out. Photo for this demo.",
        "note": "A Keelhouse plumbing project in Westerville, Ohio. Written up so neighbors in older homes know what a repipe involves.",
        "meta": [("Trade", "Plumbing"), ("Neighborhood", "Uptown Westerville"), ("Home built", "1924"), ("Time on site", "3 days"), ("Water off", "Under 4 hours a day")],
        "sections": [
            ("The problem", ["The upstairs shower barely ran, and the first water out of every tap was brown. A camera and a cut section confirmed it: the original galvanized pipe was nearly closed off with rust inside."]),
            ("What we did", ["We ran new copper mains through the basement and PEX branch lines up through closets and an existing chase, so we only had to open two small wall sections.",
                             "Water was off for under four hours each day, and every fixture worked each night. We patched the openings, tested every line at pressure, and hauled away the old pipe."]),
            ("The result", ["Pressure upstairs went from a trickle to normal, and the rusty water is gone. The homeowners have photos of every new line in their home file for the next time anyone opens a wall."]),
        ],
        "preset": "leak",
        "date": "2026-07-22",
    },
    "heat-pump-install-grove-city-oh": {
        "summary": "A 2004 Grove City ranch had a failing AC and a furnace with a few years left. We installed a cold climate heat pump and kept the gas furnace as backup for the coldest days.",
        "desc": "A dual fuel heat pump install in a 2004 ranch home in Grove City, Ohio, pairing a cold climate heat pump with the existing gas furnace.",
        "img_alt": "A new heat pump outdoor unit on a concrete pad beside a brick ranch home",
        "caption": "The new heat pump on a fresh pad, set back from the bedroom windows to keep it quiet. Photo for this demo.",
        "note": "A Keelhouse heating and cooling project in Grove City, Ohio. Written up for neighbors weighing a heat pump.",
        "meta": [("Trade", "Heating &amp; Cooling"), ("Neighborhood", "Grove City"), ("Home built", "2004"), ("Time on site", "2 days"), ("Permit", "Filed and inspected")],
        "sections": [
            ("The problem", ["The original AC was leaking refrigerant and losing more every season. The gas furnace still ran well but was nearing the end of its life. The homeowners wanted lower bills without giving up gas heat on the coldest nights."]),
            ("What we did", ["We ran a room by room load calculation, then installed a cold climate heat pump sized to the house and paired it with the existing furnace in a dual fuel setup. A new thermostat switches to gas automatically when it gets cold enough that gas is cheaper to run.",
                             "We poured a new pad, set the outdoor unit away from the bedroom windows, filed the permit and passed inspection. We also checked the utility rebate programs and filled out the paperwork for the ones they qualified for."]),
            ("The result", ["The house heats with the heat pump for most of the winter and cools more evenly in summer. The furnace now runs only on the coldest days, which should add years to its life."]),
        ],
        "preset": "install",
        "date": "2026-09-03",
    },
}
